In [1]:
import qutip as qt
from qutip import tensor, basis
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from scipy.optimize import curve_fit
from itertools import product
from quantum_logical.trotterization import Trotterization

In [2]:
# generating parameters and creating initial state
T1 = 1
T2 = .5

N = 5
dim = 2
trotter_dt = .001

# initializing Trotterization
trotter = Trotterization(trotter_dt=trotter_dt, T1=T1, T2=T2, dim=dim, num_qubits=N)

In [3]:
# creating gates
# creating the set of cnots
cnot1 = qt.cnot(N=5, control=0, target=1)
cnot2 = qt.cnot(N=5, control=0, target=2)

cnot3 = qt.cnot(N=5, control=0, target=3)
cnot4 = qt.cnot(N=5, control=1, target=3)

cnot5 = qt.cnot(N=5, control=1, target=4)
cnot6 = qt.cnot(N=5, control=2, target=4)

x_gate = qt.Qobj([[0, 1],[1, 0]])

C:\Users\girgi\AppData\Local\Temp\ipykernel_20448\2557974889.py:3: DeprecationWarning: Importing functions/classes of the qip submodule directly from the namespace qutip is deprecated. Please import them from the submodule instead, e.g.
from qutip.qip.operations import cnot
from qutip.qip.circuit import QubitCircuit

  cnot1 = qt.cnot(N=5, control=0, target=1)
C:\Users\girgi\AppData\Local\Temp\ipykernel_20448\2557974889.py:4: DeprecationWarning: Importing functions/classes of the qip submodule directly from the namespace qutip is deprecated. Please import them from the submodule instead, e.g.
from qutip.qip.operations import cnot
from qutip.qip.circuit import QubitCircuit

  cnot2 = qt.cnot(N=5, control=0, target=2)
C:\Users\girgi\AppData\Local\Temp\ipykernel_20448\2557974889.py:6: DeprecationWarning: Importing functions/classes of the qip submodule directly from the namespace qutip is deprecated. Please import them from the submodule instead, e.g.
from qutip.qip.operations import cnot

In [4]:
from quantum_logical.gate_extender import Gate_extender, Convert_levels

# new set of qutrit gates
gate_extention = Gate_extender(num_qubits=N)
cnot3_new, new_dim = gate_extention.qubit_to_qudit(gate=cnot3, from_dim=2, to_dim=3)
cnot4_new, new_dim = gate_extention.qubit_to_qudit(gate=cnot4, from_dim=2, to_dim=3)
cnot5_new, new_dim = gate_extention.qubit_to_qudit(gate=cnot5, from_dim=2, to_dim=3)
cnot6_new, new_dim = gate_extention.qubit_to_qudit(gate=cnot6, from_dim=2, to_dim=3)

# these cnots as presnetly constructed will move have the same target qubits as before but now they have been increased in dimensionality 
converter = Convert_levels(num_qubits=N)
cnot3 = converter.level_conversion(levels=[1,2], dim=new_dim, gate=cnot3_new)
cnot4 = converter.level_conversion(levels=[1,2], dim=new_dim, gate=cnot4_new)
cnot5 = converter.level_conversion(levels=[1,2], dim=new_dim, gate=cnot5_new)
cnot6 = converter.level_conversion(levels=[1,2], dim=new_dim, gate=cnot6_new)
dim = new_dim

In [6]:
# build the circuit 

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]